# Generated by Django 3.0.8 on 2022-04-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_beats', '0002_useraccount_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='tag',
            new_name='cart',
        ),
    ]
