# Generated by Django 3.0.8 on 2022-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_beats', '0005_auto_20220513_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='linkToFullLicense',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='playlist',
            name='linkToMp3License',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='playlist',
            name='linkToWavLicense',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='playlist',
            name='plays_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='purchased',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='cart',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
