# Generated by Django 3.0.8 on 2022-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_beats', '0007_auto_20220622_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='playlist',
            name='mood',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
