# Generated by Django 3.0.8 on 2022-07-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_beats', '0008_auto_20220628_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='price',
            new_name='mp3Price',
        ),
        migrations.AddField(
            model_name='playlist',
            name='trackout',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='unlimited',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='wavPrice',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
